### ISSUE TITLE
K8s / AWS meta attributes for push metrics

### ISSUE THREAD

**Issue by szibis** [VictoriaMetrics/VictoriaMetrics#6969]
### Is your question request related to a specific component?

Push metrics especially OTEL additional metadata discovery from infrastructure like K8s/AWS.

### Describe the question in detail

Any push format and especially OTEL once pushed not having metadata from infrastructure like AWS/k8s or other. 
In OTEL collector we have for example [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md).
Is there any plans to have such thing in VMagent most probably ? or is there is undocumented feature similar to scrape can offer for metadata add ?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
Hey @szibis 
VictoriaMetrics/VictoriaLogs only supports receiving OTEL data from collector, all data transformations are expected to be done on collector's site

**Comment by szibis** [comment]
Ok thanks for clarification
